
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yessy Permatasari
 */
public class Transaksi extends javax.swing.JFrame {
   String nol_jam ="";
String nol_menit = "";
String nol_detik = "";

    /**
     * Creates new form Transaksi
     */
    public Transaksi() {
        initComponents();
           setTanggal();
            setJam();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        txtid = new javax.swing.JTextField();
        jmlbrg = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtdiskon = new javax.swing.JTextField();
        txthargabarang = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtnamakasir = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txttanggal = new com.toedter.calendar.JDateChooser();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        labeltanggal = new javax.swing.JLabel();
        labeljam = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnamabarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ttlbrg = new javax.swing.JTextField();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 270, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setText("Id Barang");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(40, 190, 90, 20);

        jLabel3.setText("Jumlah Barang");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 320, 120, 20);

        jButton1.setText("PRINT");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1010, 120, 79, 29);
        getContentPane().add(txtid);
        txtid.setBounds(170, 180, 330, 40);
        getContentPane().add(jmlbrg);
        jmlbrg.setBounds(170, 310, 330, 40);

        jLabel4.setText("Harga Barang");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(40, 380, 110, 20);
        getContentPane().add(txtdiskon);
        txtdiskon.setBounds(170, 440, 180, 50);
        getContentPane().add(txthargabarang);
        txthargabarang.setBounds(170, 360, 330, 50);

        jLabel5.setText("Diskon");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(60, 460, 48, 20);

        jLabel6.setText("Nama Kasir");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(50, 520, 110, 20);
        getContentPane().add(txtnamakasir);
        txtnamakasir.setBounds(170, 510, 330, 50);

        jLabel7.setText("Tanggal");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 590, 70, 20);
        getContentPane().add(txttanggal);
        txttanggal.setBounds(170, 570, 330, 50);

        jButton2.setText("Diskon");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(370, 440, 140, 50);

        jButton4.setText("DELETE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(660, 120, 89, 29);

        jButton5.setText("CLEAR");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(770, 120, 81, 29);

        jButton6.setText("REFRESH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(880, 120, 110, 29);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "namabarang", "hargabarang", "tgltransaksi", "namakasir", "jmlbarang", "total"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(520, 170, 590, 510);

        labeltanggal.setText("Tanggal");
        getContentPane().add(labeltanggal);
        labeltanggal.setBounds(930, 20, 170, 20);

        labeljam.setText("Jam");
        getContentPane().add(labeljam);
        labeljam.setBounds(940, 70, 160, 20);

        jLabel8.setText("Nama Barang");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 260, 95, 20);
        getContentPane().add(txtnamabarang);
        txtnamabarang.setBounds(170, 240, 330, 50);

        jLabel9.setText("Total");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(50, 640, 110, 20);
        getContentPane().add(ttlbrg);
        ttlbrg.setBounds(170, 630, 200, 50);

        jButton8.setText("Total");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(380, 630, 120, 50);

        jButton7.setText("SAVE");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(550, 120, 93, 29);

        jPanel2.setBackground(new java.awt.Color(255, 153, 102));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 0, 1120, 640);

        setSize(new java.awt.Dimension(1142, 758));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
     
     
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
           int baris = jTable1.getSelectedRow();
        if (baris != -1) {
            String id = jTable1.getValueAt(baris, 0).toString();
            String SQL = "DELETE FROM tb_barang WHERE id='"+id+"'";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus","Sukses",JOptionPane.INFORMATION_MESSAGE);
                 
            } else {
                JOptionPane.showMessageDialog(this, "Data Gagal Dihapus","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih Barisnya Terlebih Dahulu","Error",JOptionPane.WARNING_MESSAGE);
        }         // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    txtid.setText("");
    jmlbrg.setText("");
    txthargabarang.setText("");
    txtdiskon.setText("");
    txtnamakasir.setText("");
    txttanggal.setDate(null);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    selectData();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      MessageFormat header = new MessageFormat ("BTransaksi Barang");
    MessageFormat footer = new MessageFormat ("Page(0,number,integer)         ");
    try {
        jTable1.print(JTable.PrintMode.FIT_WIDTH, header , footer , true , null , true , null);
    } catch (java.awt.print.PrinterException e) {
        System.err.format("Cannot print %s%n", e.getMessage());
    }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int harga = Integer.parseInt(txthargabarang.getText().toString());
if(harga >= 100000) {
        int diskon = harga*50/100;
        txtdiskon.setText(""+diskon);

}  else {
    txtdiskon.setText(""+0);
}      // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
    int jumlah = Integer.parseInt(jmlbrg.getText().toString());  
    int harga = Integer.parseInt(txthargabarang.getText().toString());
    int total = jumlah*harga;
    ttlbrg.setText(""+total); // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
           SimpleDateFormat dateFormat = new SimpleDateFormat("yyy-MM-dd");
        String tanggal = dateFormat.format(txttanggal.getDate());

        if ("".equals(txtid.getText()) || "".equals(txtnamabarang.getText()) || "".equals(txthargabarang.getText()) ||"".equals(tanggal) || "".equals(txtnamakasir.getText())||"".equals(jmlbrg.getText())||"".equals(ttlbrg.getText())) {
            {  JOptionPane.showMessageDialog(this, " Harap Lengkapi Data","Error", JOptionPane.WARNING_MESSAGE);}
          String SQL = "INSERT INTO tb_barang(id,namabarang,hargabarang,tgltransaksi,namakasir,jmlbarang,total)"+ "VALUES('"+txtid.getText()+"','"+txtnamabarang.getText()+"','"+txthargabarang.getText()+"','"+tanggal+"','"+txtnamakasir.getText()+"','"+jmlbrg.getText()+"','"+ttlbrg.getText()+"')";
            int status = KoneksiDB.execute(SQL);
            if (status==1) {
                JOptionPane.showMessageDialog(this,"Data berhasil ditambahkan","Sukses",JOptionPane.INFORMATION_MESSAGE);
                selectData();
            }
            else{
                JOptionPane.showMessageDialog(this,"Data gagal ditambahkan","Gagal",JOptionPane.WARNING_MESSAGE);
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Transaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Transaksi().setVisible(true);
            }
        });
    }
    public void setTanggal() {
    java.util.Date skrg = new java.util.Date();
    java.text.SimpleDateFormat kal = new
    java.text.SimpleDateFormat("dd/MM/yyyy");
    labeltanggal.setText(kal.format(skrg));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jmlbrg;
    private javax.swing.JLabel labeljam;
    private javax.swing.JLabel labeltanggal;
    private javax.swing.JTextField ttlbrg;
    private javax.swing.JTextField txtdiskon;
    private javax.swing.JTextField txthargabarang;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnamabarang;
    private javax.swing.JTextField txtnamakasir;
    private com.toedter.calendar.JDateChooser txttanggal;
    // End of variables declaration//GEN-END:variables

    private void selectData() {
        
        String kolom[]={"id","namabarang","hargabarang","tgltransaksi","namakasir","jmlbarang","total"};
        DefaultTableModel dtm = new DefaultTableModel(null, kolom);   
        String SQL = "SELECT * FROM tb_barang";
        ResultSet rs = KoneksiDB.executeQuery(SQL);
            try{
            while(rs.next()){
                String id = rs.getString(1);
                String namabarang = rs.getString(2);
                String hargabarang = rs.getString(3);
                String namakasir = rs.getString(5);
                String tanggal = rs.getString(4);
                String total = rs.getString(7);
                String jumlah = rs.getString(6);
                  
                   
                    String data[] = {id,namabarang,hargabarang,tanggal,namakasir,jumlah,total};
                    dtm.addRow(data);
            }
        }   catch(SQLException ex){
                    Logger.getLogger(Transaksi.class.getName()).log(Level.SEVERE,null, ex);
                    }
            jTable1.setModel(dtm);     //To change body of generated methods, choose Tools | Templates.
    }
     public void setJam() {
           ActionListener taskPerformer;
        taskPerformer = new ActionListener(){
            String nol_hour,nol_minute,nol_sec;
            public void actionPerformed(ActionEvent evt){
                Date dt=new Date();
                int hour=dt.getHours();
                int minute=dt.getMinutes();
                int sec=dt.getSeconds();
                if (hour<=9) {
                    nol_hour="0";
                }
                if(minute<=9){
                    nol_minute="0";
                }
                if(sec<=9){
                    nol_sec="0";
                }
                String jam=Integer.toString(hour);
                String menit=Integer.toString(minute);
                String detik=Integer.toString(sec);
                labeljam.setText(jam+" : "+menit+" : "+detik);
            }

        };
        new Timer(100, taskPerformer).start();//To change body of generated methods, choose Tools | Templates.
    }
}
